#! /bin/sh

cd ~/.vim && git pull --rebase origin master
ln -sfF ~/.vim/.vimrc ~/.vimrc
# ln -sfF ~/.vim/.vimrc ~/.vim/init.vim
# ln -sfF ~/.vim ~/.config/nvim

if [ "$1" = "init" ]; then
  cd ~/.vim && git clone https://github.com/k-takata/minpac.git pack/minipac/opt/minipac
fi
